/*
 * generated by Xtext 2.12.0
 */
package org.xtext.icam.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.icam.statemachine.ui.internal.StatemachineActivator;

public class StateMachineUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return StatemachineActivator.getInstance().getInjector("org.xtext.icam.StateMachine");
	}

}
