/*
 * generated by Xtext 2.12.0
 */
package org.xtext.icam.validation

//import org.eclipse.xtext.validation.Check
//import org.xtext.icam.stateMachine.StateMachine

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class StateMachineValidator extends AbstractStateMachineValidator {
	
	
	
}
