/**
 * generated by Xtext 2.12.0
 */
package org.xtext.icam.stateMachine;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declared Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.icam.stateMachine.DeclaredParameter#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.icam.stateMachine.StateMachinePackage#getDeclaredParameter()
 * @model
 * @generated
 */
public interface DeclaredParameter extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(VarName)
   * @see org.xtext.icam.stateMachine.StateMachinePackage#getDeclaredParameter_Name()
   * @model containment="true"
   * @generated
   */
  VarName getName();

  /**
   * Sets the value of the '{@link org.xtext.icam.stateMachine.DeclaredParameter#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(VarName value);

} // DeclaredParameter
