/**
 * generated by Xtext 2.12.0
 */
package org.xtext.icam.stateMachine;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Modifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.icam.stateMachine.Modifier#getVisibility <em>Visibility</em>}</li>
 * </ul>
 *
 * @see org.xtext.icam.stateMachine.StateMachinePackage#getModifier()
 * @model
 * @generated
 */
public interface Modifier extends EObject
{
  /**
   * Returns the value of the '<em><b>Visibility</b></em>' attribute list.
   * The list contents are of type {@link org.xtext.icam.stateMachine.Visibility}.
   * The literals are from the enumeration {@link org.xtext.icam.stateMachine.Visibility}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Visibility</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visibility</em>' attribute list.
   * @see org.xtext.icam.stateMachine.Visibility
   * @see org.xtext.icam.stateMachine.StateMachinePackage#getModifier_Visibility()
   * @model unique="false"
   * @generated
   */
  EList<Visibility> getVisibility();

} // Modifier
