/**
 * generated by Xtext 2.12.0
 */
package org.xtext.icam.stateMachine;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>State Machine</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.icam.stateMachine.StateMachine#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.icam.stateMachine.StateMachine#getEvents <em>Events</em>}</li>
 *   <li>{@link org.xtext.icam.stateMachine.StateMachine#getCommands <em>Commands</em>}</li>
 *   <li>{@link org.xtext.icam.stateMachine.StateMachine#getStates <em>States</em>}</li>
 *   <li>{@link org.xtext.icam.stateMachine.StateMachine#getInitialstates <em>Initialstates</em>}</li>
 *   <li>{@link org.xtext.icam.stateMachine.StateMachine#getFinalstates <em>Finalstates</em>}</li>
 * </ul>
 *
 * @see org.xtext.icam.stateMachine.StateMachinePackage#getStateMachine()
 * @model
 * @generated
 */
public interface StateMachine extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.icam.stateMachine.StateMachinePackage#getStateMachine_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.icam.stateMachine.StateMachine#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Events</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.icam.stateMachine.Event}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Events</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Events</em>' containment reference list.
   * @see org.xtext.icam.stateMachine.StateMachinePackage#getStateMachine_Events()
   * @model containment="true"
   * @generated
   */
  EList<Event> getEvents();

  /**
   * Returns the value of the '<em><b>Commands</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.icam.stateMachine.Command}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Commands</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Commands</em>' containment reference list.
   * @see org.xtext.icam.stateMachine.StateMachinePackage#getStateMachine_Commands()
   * @model containment="true"
   * @generated
   */
  EList<Command> getCommands();

  /**
   * Returns the value of the '<em><b>States</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.icam.stateMachine.State}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>States</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>States</em>' containment reference list.
   * @see org.xtext.icam.stateMachine.StateMachinePackage#getStateMachine_States()
   * @model containment="true"
   * @generated
   */
  EList<State> getStates();

  /**
   * Returns the value of the '<em><b>Initialstates</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Initialstates</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initialstates</em>' reference.
   * @see #setInitialstates(State)
   * @see org.xtext.icam.stateMachine.StateMachinePackage#getStateMachine_Initialstates()
   * @model
   * @generated
   */
  State getInitialstates();

  /**
   * Sets the value of the '{@link org.xtext.icam.stateMachine.StateMachine#getInitialstates <em>Initialstates</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Initialstates</em>' reference.
   * @see #getInitialstates()
   * @generated
   */
  void setInitialstates(State value);

  /**
   * Returns the value of the '<em><b>Finalstates</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Finalstates</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Finalstates</em>' reference.
   * @see #setFinalstates(State)
   * @see org.xtext.icam.stateMachine.StateMachinePackage#getStateMachine_Finalstates()
   * @model
   * @generated
   */
  State getFinalstates();

  /**
   * Sets the value of the '{@link org.xtext.icam.stateMachine.StateMachine#getFinalstates <em>Finalstates</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Finalstates</em>' reference.
   * @see #getFinalstates()
   * @generated
   */
  void setFinalstates(State value);

} // StateMachine
