/**
 * generated by Xtext 2.12.0
 */
package org.xtext.icam.stateMachine;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.icam.stateMachine.StateMachinePackage#getStringType()
 * @model
 * @generated
 */
public interface StringType extends Type
{
} // StringType
