/*
 * generated by Xtext 2.12.0
 */
package org.xtext.icam.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractStateMachineScopeProvider extends DelegatingScopeProvider {
}
