/**
 * generated by Xtext 2.12.0
 */
package org.xtext.icam.stateMachine.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.icam.stateMachine.FloatType;
import org.xtext.icam.stateMachine.StateMachinePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Float Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FloatTypeImpl extends TypeImpl implements FloatType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FloatTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return StateMachinePackage.Literals.FLOAT_TYPE;
  }

} //FloatTypeImpl
