/**
 * generated by Xtext 2.12.0
 */
package org.xtext.icam.stateMachine.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.icam.stateMachine.Command;
import org.xtext.icam.stateMachine.Event;
import org.xtext.icam.stateMachine.State;
import org.xtext.icam.stateMachine.StateMachine;
import org.xtext.icam.stateMachine.StateMachinePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>State Machine</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.icam.stateMachine.impl.StateMachineImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.icam.stateMachine.impl.StateMachineImpl#getEvents <em>Events</em>}</li>
 *   <li>{@link org.xtext.icam.stateMachine.impl.StateMachineImpl#getCommands <em>Commands</em>}</li>
 *   <li>{@link org.xtext.icam.stateMachine.impl.StateMachineImpl#getStates <em>States</em>}</li>
 *   <li>{@link org.xtext.icam.stateMachine.impl.StateMachineImpl#getInitialevents <em>Initialevents</em>}</li>
 *   <li>{@link org.xtext.icam.stateMachine.impl.StateMachineImpl#getFinalevents <em>Finalevents</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StateMachineImpl extends MinimalEObjectImpl.Container implements StateMachine
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getEvents() <em>Events</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEvents()
   * @generated
   * @ordered
   */
  protected EList<Event> events;

  /**
   * The cached value of the '{@link #getCommands() <em>Commands</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCommands()
   * @generated
   * @ordered
   */
  protected EList<Command> commands;

  /**
   * The cached value of the '{@link #getStates() <em>States</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStates()
   * @generated
   * @ordered
   */
  protected EList<State> states;

  /**
   * The cached value of the '{@link #getInitialevents() <em>Initialevents</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInitialevents()
   * @generated
   * @ordered
   */
  protected EList<State> initialevents;

  /**
   * The cached value of the '{@link #getFinalevents() <em>Finalevents</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFinalevents()
   * @generated
   * @ordered
   */
  protected EList<State> finalevents;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StateMachineImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return StateMachinePackage.Literals.STATE_MACHINE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, StateMachinePackage.STATE_MACHINE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Event> getEvents()
  {
    if (events == null)
    {
      events = new EObjectContainmentEList<Event>(Event.class, this, StateMachinePackage.STATE_MACHINE__EVENTS);
    }
    return events;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Command> getCommands()
  {
    if (commands == null)
    {
      commands = new EObjectContainmentEList<Command>(Command.class, this, StateMachinePackage.STATE_MACHINE__COMMANDS);
    }
    return commands;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<State> getStates()
  {
    if (states == null)
    {
      states = new EObjectContainmentEList<State>(State.class, this, StateMachinePackage.STATE_MACHINE__STATES);
    }
    return states;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<State> getInitialevents()
  {
    if (initialevents == null)
    {
      initialevents = new EObjectResolvingEList<State>(State.class, this, StateMachinePackage.STATE_MACHINE__INITIALEVENTS);
    }
    return initialevents;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<State> getFinalevents()
  {
    if (finalevents == null)
    {
      finalevents = new EObjectResolvingEList<State>(State.class, this, StateMachinePackage.STATE_MACHINE__FINALEVENTS);
    }
    return finalevents;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case StateMachinePackage.STATE_MACHINE__EVENTS:
        return ((InternalEList<?>)getEvents()).basicRemove(otherEnd, msgs);
      case StateMachinePackage.STATE_MACHINE__COMMANDS:
        return ((InternalEList<?>)getCommands()).basicRemove(otherEnd, msgs);
      case StateMachinePackage.STATE_MACHINE__STATES:
        return ((InternalEList<?>)getStates()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case StateMachinePackage.STATE_MACHINE__NAME:
        return getName();
      case StateMachinePackage.STATE_MACHINE__EVENTS:
        return getEvents();
      case StateMachinePackage.STATE_MACHINE__COMMANDS:
        return getCommands();
      case StateMachinePackage.STATE_MACHINE__STATES:
        return getStates();
      case StateMachinePackage.STATE_MACHINE__INITIALEVENTS:
        return getInitialevents();
      case StateMachinePackage.STATE_MACHINE__FINALEVENTS:
        return getFinalevents();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case StateMachinePackage.STATE_MACHINE__NAME:
        setName((String)newValue);
        return;
      case StateMachinePackage.STATE_MACHINE__EVENTS:
        getEvents().clear();
        getEvents().addAll((Collection<? extends Event>)newValue);
        return;
      case StateMachinePackage.STATE_MACHINE__COMMANDS:
        getCommands().clear();
        getCommands().addAll((Collection<? extends Command>)newValue);
        return;
      case StateMachinePackage.STATE_MACHINE__STATES:
        getStates().clear();
        getStates().addAll((Collection<? extends State>)newValue);
        return;
      case StateMachinePackage.STATE_MACHINE__INITIALEVENTS:
        getInitialevents().clear();
        getInitialevents().addAll((Collection<? extends State>)newValue);
        return;
      case StateMachinePackage.STATE_MACHINE__FINALEVENTS:
        getFinalevents().clear();
        getFinalevents().addAll((Collection<? extends State>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case StateMachinePackage.STATE_MACHINE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case StateMachinePackage.STATE_MACHINE__EVENTS:
        getEvents().clear();
        return;
      case StateMachinePackage.STATE_MACHINE__COMMANDS:
        getCommands().clear();
        return;
      case StateMachinePackage.STATE_MACHINE__STATES:
        getStates().clear();
        return;
      case StateMachinePackage.STATE_MACHINE__INITIALEVENTS:
        getInitialevents().clear();
        return;
      case StateMachinePackage.STATE_MACHINE__FINALEVENTS:
        getFinalevents().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case StateMachinePackage.STATE_MACHINE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case StateMachinePackage.STATE_MACHINE__EVENTS:
        return events != null && !events.isEmpty();
      case StateMachinePackage.STATE_MACHINE__COMMANDS:
        return commands != null && !commands.isEmpty();
      case StateMachinePackage.STATE_MACHINE__STATES:
        return states != null && !states.isEmpty();
      case StateMachinePackage.STATE_MACHINE__INITIALEVENTS:
        return initialevents != null && !initialevents.isEmpty();
      case StateMachinePackage.STATE_MACHINE__FINALEVENTS:
        return finalevents != null && !finalevents.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //StateMachineImpl
