/**
 * generated by Xtext 2.12.0
 */
package org.xtext.icam.stateMachine.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.icam.stateMachine.StateMachinePackage;
import org.xtext.icam.stateMachine.StringType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>String Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StringTypeImpl extends TypeImpl implements StringType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StringTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return StateMachinePackage.Literals.STRING_TYPE;
  }

} //StringTypeImpl
